[update]
usage = '''
arg "<tool>" {
  choices "all" "antidote" "claude" "skills"
  default "all"
}
'''
run = '''
#!/usr/bin/env bash
[ "${usage_tool}" = all ] && usage_tool='*'
exec {{mise_bin}} run "update:${usage_tool}"
'''

["update:skills"]
run = "bunx skills update --global"
hide = true
