[upgrade]
usage = '''
arg "<tool>" {
  choices "all" "brew" "mise"
  default "all"
}
'''
run = '''
#!/usr/bin/env bash
[ "${usage_tool}" = all ] && usage_tool='*'
exec {{mise_bin}} run "upgrade:${usage_tool}"
'''

["upgrade:brew"]
run = ["brew update", "brew upgrade", "brew cleanup --prune=all"]
hide = true

["upgrade:mise"]
run = ["{{mise_bin}} upgrade", "{{mise_bin}} reshim", "{{mise_bin}} cache prune"]
hide = true
