[tools]
node = "lts"
deno = "latest"
bun = "latest"
python = "3.12"
uv = "latest"
java = "temurin-21"
"npm:commitizen" = "latest"
"npm:cz-conventional-changelog" = "latest"
"pipx:commitizen" = "latest"
"pipx:pre-commit" = "latest"
"pipx:ruff" = "latest"
"pipx:sqlfluff" = "latest"
"pipx:pylyzer" = "latest"

[tasks."upgrade:brew"]
run = ["brew update", "brew upgrade", "brew cleanup --prune=all"]

[tasks."upgrade:mise"]
run = ["mise upgrade", "mise reshim", "mise cache prune"]

[tasks.upgrade]
depends = ["upgrade:*"]

[tasks."prune:node"]
run = [
    "find . -type d -name 'node_modules' -exec rm -rf {} +",
    "find . -type f -name '.eslintcache' -exec rm -rf {} +",
    "find . -type f -name '.stylelintcache' -exec rm -rf {} +",
]

[tasks."prune:python"]
run = [
    "find . -type f -name '*.py[co]' -delete",
    "find . -type d -name '__pycache__' -exec rm -rf {} +",
    "find . -type d -name '.mypy_cache' -exec rm -rf {} +",
    "find . -type d -name '.ruff_cache' -exec rm -rf {} +",
    "find . -type d -name '.pytest_cache' -exec rm -rf {} +",
]

[tasks.prune]
depends = ["prune:*"]

[settings]

[settings.npm]
bun = true

[settings.pipx]
uvx = true
